server.port: 8080
spring.profiles: default
spring.datasource:
  url: "jdbc:h2:mem:testdb;MODE=MySQL"
  driverClassName: org.h2.Driver
  username: sa
  password: ""
  platform: jdbc
spring.h2.console.enabled: true
spring:
  thymeleaf:
    cache: false
logging:
  level:
    com.captcha: DEBUG
    redis.clients.jedis: DEBUG    
captcha:
  enabled: false
  secret: 6LcV_hkUAAAAALcgjaJ_pa4_5w-1F7uTl6e0z9HM
    