server.port: 8080
spring.profiles: default
spring.datasource:
  url: "jdbc:h2:mem:testdb;MODE=MySQL"
  driverClassName: org.h2.Driver
  username: sa
  password: ""
  platform: jdbc
spring.h2.console.enabled: true
spring:
  thymeleaf:
    cache: false
logging:
  level:
    com.captcha: DEBUG
    